import type { ReactNode } from "react";
import { LockKeyhole, ShieldCheck } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";

export function AdminLoginShell({ children }: { children: ReactNode }) {
  return <main className="min-h-dvh bg-[var(--canvas)] xl:grid xl:grid-cols-[minmax(340px,0.8fr)_minmax(640px,1.2fr)]">
    <aside className="relative hidden overflow-hidden border-r border-[var(--line)] bg-[var(--side-panel)] px-10 py-9 xl:flex xl:min-h-dvh xl:flex-col">
      <div className="absolute inset-0 opacity-40 [background-image:linear-gradient(to_right,var(--line)_1px,transparent_1px),linear-gradient(to_bottom,var(--line)_1px,transparent_1px)] [background-size:40px_40px]" />
      <div className="relative flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-[8px] bg-[var(--danger)] text-[12px] font-bold text-white">S</span><div><p className="text-[15px] font-semibold tracking-[-0.03em] text-[var(--ink)]">Kuberise Capital</p><p className="font-mono text-[9px] tracking-[0.14em] text-[var(--danger)]">ADMIN PORTAL</p></div></div>
      <div className="relative my-auto max-w-sm pb-20"><p className="mb-5 font-mono text-[11px] font-medium tracking-[0.14em] text-[var(--danger)]">CONTROL PLANE</p><h1 className="text-[clamp(2.7rem,4.4vw,4.5rem)] font-semibold leading-[0.96] tracking-[-0.067em] text-[var(--ink)]">Decisive control. Deliberate access.</h1><p className="mt-7 max-w-[36ch] text-[15px] leading-6 text-[var(--ink-muted)]">Administrative authority is isolated from the client portal and verified at every protected boundary.</p></div>
      <div className="relative rounded-xl border border-[var(--line-strong)] bg-[color-mix(in_srgb,var(--panel)_72%,transparent)] p-4"><div className="flex items-center gap-2 text-[var(--danger)]"><ShieldCheck size={15} /><span className="font-mono text-[10px] tracking-[0.1em]">SUPER ADMIN ONLY</span></div><p className="mt-2 text-[12px] leading-5 text-[var(--ink-muted)]">This workspace is provisioned from server configuration. There is no public administrator registration.</p></div>
    </aside>
    <section className="flex min-h-dvh flex-col px-5 py-5 sm:px-8 sm:py-7 xl:px-14 xl:py-9"><header className="flex items-center justify-between"><div className="flex items-center gap-2.5 xl:hidden"><span className="grid h-7 w-7 place-items-center rounded-[7px] bg-[var(--danger)] text-[11px] font-bold text-white">S</span><span><span className="block text-[14px] font-semibold tracking-[-0.03em] text-[var(--ink)]">Kuberise Capital</span><span className="block font-mono text-[8px] tracking-[0.12em] text-[var(--danger)]">ADMIN PORTAL</span></span></div><div className="ml-auto"><ThemeToggle /></div></header><div className="mx-auto flex w-full max-w-[440px] flex-1 flex-col justify-center py-10"><div className="mb-7 flex items-center gap-2 text-[var(--ink-subtle)]"><LockKeyhole size={14} /><span className="font-mono text-[10px] tracking-[0.1em]">RESTRICTED WORKSPACE</span></div>{children}</div><footer className="flex min-h-6 items-center justify-between font-mono text-[10px] tracking-[0.04em] text-[var(--ink-subtle)]"><span>KUBERISE CAPITAL SYSTEMS</span><span>ADMIN ACCESS</span></footer></section>
  </main>;
}
